import { useForm } from 'react-hook-form'
import { MachineSpec } from '../utils/machines'
import { CreateMachineForm } from '../types/create-machine'

// export const useCreateMachineForm = () => {
//     return useForm<MachineSpec>({
//         defaultValues: {
//             name: '', //generatedName
//             machineClass: '',
//             machineType: '',
//             size,
//             // cpu: defaultCPU,
//             // memory: 2147483648, // 2Gi in bytes, given from smallTeamplate vitistack
//             disks: [rootDisk],
//             network: defaultNetwork,
//             os: defaultOS,
//             provider: 'kubervirt', //kubevirt eller proxmox
//             providerConfig: defaultProviderConfig,
//             sshKeys: [],
//             userData: '',
//             tags: {},
//             securityGroups: [],
//             monitoring: false,
//             backup: defaultBackup,
//             cloudInit: cloudInitConfig,
//         }
//     })
// }

export const useCreateMachineForm = () => {
  return useForm<CreateMachineForm>({
    defaultValues: {
      name: '', //generatedName
      machineClass: '',
      machineType: '',
      size: 'small', //provides information to cpu, memory and disk
      network: 'default', //uses default network template from networkTemplates
    },
  })
}

//default cpu, small, given by template in vitistack
export const defaultCPU = {
  cores: 1,
  threadsPerCore: 1,
  sockets: 1,
}

export const rootDisk = {
  name: 'root',
  sizeGB: 20,
  type: 'standard',
  boot: true,
  device: '',
  encrypted: false,
  iops: 100, //min 100, max 64000
  throughput: 125, //min 125, max 4000
}

// export const defaultNetwork = {
//     networkNamespaceName: '', //generated by the kubernetes cluster
//     vpc: '',
//     subnet: '',
//     assignPublicIP: false,
//     privateIP: '',
//     publicIP: '',
//     interfaces: [
//         {
//             name: '',
//             subnet: '',
//             securityGroups: [],
//             primary: true,
//         },
//     ],
// }

export const defaultOS = {
  family: '',
  distribution: '',
  version: '',
  architecture: '',
  imageID: '',
  isoUri: '',
  imageFamily: '',
}

export const defaultProviderConfig = {
  name: '', //(aws, azure, gcp, vsphere, openstack)
  region: '', //fix map like cluster page
  zone: '',
  config: {},
  credentialsRef: {
    secretName: '',
    namespace: '',
  },
}

export const defaultBackup = {
  enabled: false,
  schedule: '',
  retention: 0,
}

export const cloudInitConfig = {
  type: '',
  userData: '',
  userDataBase64: '',
  networkData: '',
  networkDataBase64: '',
  userDataSecretRef: {
    name: '',
    key: '',
  },
  networkDataSecretRef: {
    name: '',
    key: '',
  },
  userDataConfigMapRef: {
    name: '',
    key: '',
  },
  networkDataConfigMapRef: {
    name: '',
    key: '',
  },
}
